debug: false
server:
  hostname: localhost
  port: 8080
  ssl: false
  gql_introspection: true
  origins:
    - http://localhost:8080
    - http://localhost:3000
database:
  username: cble
  password: cble
  host: db
  ssl: false
providers:
  cache: ./providers-cache
auth:
  jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  session_timeout: 24h0m0s
initialization:
  default_admin:
    first_name: CBLE
    last_name: Admin
    username: cble
    password: cble
  default_project: default
  admin_group: CBLE Administrators
deployments:
  auto_suspend_time: 3h0m0s
  lease_time: 2160h0m0s # 90 days
project_defaults:
  quota_cpu: 10
  quota_ram: 32768 # 32 GiB
  quota_disk: 131072 # 128 GiB
  quota_network: 1
  quota_router: 1
