fragment UserFragment on User {
  id
  createdAt
  updatedAt
  username
  email
  firstName
  lastName
}

query Me {
  me {
    ...UserFragment
  }
}

query ListUsers($count: Int! = 10, $offset: Int) {
  users(count: $count, offset: $offset) {
    users {
      ...UserFragment
    }
    total
  }
}

query MeHasPermission(
  $objectType: ObjectType!
  $objectID: ID
  $action: Action!
) {
  meHasPermission(objectType: $objectType, objectID: $objectID, action: $action)
}

query SearchUsers($search: String!) {
  searchUsers(search: $search, count: 5) {
    users {
      ...UserFragment
    }
  }
}
