// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cble-platform/cble-backend/ent/blueprint"
	entprovider "github.com/cble-platform/cble-backend/ent/provider"
	"github.com/google/uuid"
)

// ProviderCreate is the builder for creating a Provider entity.
type ProviderCreate struct {
	config
	mutation *ProviderMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pc *ProviderCreate) SetCreatedAt(t time.Time) *ProviderCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *ProviderCreate) SetNillableCreatedAt(t *time.Time) *ProviderCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *ProviderCreate) SetUpdatedAt(t time.Time) *ProviderCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *ProviderCreate) SetNillableUpdatedAt(t *time.Time) *ProviderCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetDisplayName sets the "display_name" field.
func (pc *ProviderCreate) SetDisplayName(s string) *ProviderCreate {
	pc.mutation.SetDisplayName(s)
	return pc
}

// SetProviderGitURL sets the "provider_git_url" field.
func (pc *ProviderCreate) SetProviderGitURL(s string) *ProviderCreate {
	pc.mutation.SetProviderGitURL(s)
	return pc
}

// SetProviderVersion sets the "provider_version" field.
func (pc *ProviderCreate) SetProviderVersion(s string) *ProviderCreate {
	pc.mutation.SetProviderVersion(s)
	return pc
}

// SetConfigBytes sets the "config_bytes" field.
func (pc *ProviderCreate) SetConfigBytes(b []byte) *ProviderCreate {
	pc.mutation.SetConfigBytes(b)
	return pc
}

// SetIsLoaded sets the "is_loaded" field.
func (pc *ProviderCreate) SetIsLoaded(b bool) *ProviderCreate {
	pc.mutation.SetIsLoaded(b)
	return pc
}

// SetNillableIsLoaded sets the "is_loaded" field if the given value is not nil.
func (pc *ProviderCreate) SetNillableIsLoaded(b *bool) *ProviderCreate {
	if b != nil {
		pc.SetIsLoaded(*b)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *ProviderCreate) SetID(u uuid.UUID) *ProviderCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *ProviderCreate) SetNillableID(u *uuid.UUID) *ProviderCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// AddBlueprintIDs adds the "blueprints" edge to the Blueprint entity by IDs.
func (pc *ProviderCreate) AddBlueprintIDs(ids ...uuid.UUID) *ProviderCreate {
	pc.mutation.AddBlueprintIDs(ids...)
	return pc
}

// AddBlueprints adds the "blueprints" edges to the Blueprint entity.
func (pc *ProviderCreate) AddBlueprints(b ...*Blueprint) *ProviderCreate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return pc.AddBlueprintIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (pc *ProviderCreate) Mutation() *ProviderMutation {
	return pc.mutation
}

// Save creates the Provider in the database.
func (pc *ProviderCreate) Save(ctx context.Context) (*Provider, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProviderCreate) SaveX(ctx context.Context) *Provider {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProviderCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProviderCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *ProviderCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := entprovider.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := entprovider.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.IsLoaded(); !ok {
		v := entprovider.DefaultIsLoaded
		pc.mutation.SetIsLoaded(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := entprovider.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProviderCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Provider.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Provider.updated_at"`)}
	}
	if _, ok := pc.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Provider.display_name"`)}
	}
	if _, ok := pc.mutation.ProviderGitURL(); !ok {
		return &ValidationError{Name: "provider_git_url", err: errors.New(`ent: missing required field "Provider.provider_git_url"`)}
	}
	if _, ok := pc.mutation.ProviderVersion(); !ok {
		return &ValidationError{Name: "provider_version", err: errors.New(`ent: missing required field "Provider.provider_version"`)}
	}
	if _, ok := pc.mutation.ConfigBytes(); !ok {
		return &ValidationError{Name: "config_bytes", err: errors.New(`ent: missing required field "Provider.config_bytes"`)}
	}
	if _, ok := pc.mutation.IsLoaded(); !ok {
		return &ValidationError{Name: "is_loaded", err: errors.New(`ent: missing required field "Provider.is_loaded"`)}
	}
	return nil
}

func (pc *ProviderCreate) sqlSave(ctx context.Context) (*Provider, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProviderCreate) createSpec() (*Provider, *sqlgraph.CreateSpec) {
	var (
		_node = &Provider{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(entprovider.Table, sqlgraph.NewFieldSpec(entprovider.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(entprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(entprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.DisplayName(); ok {
		_spec.SetField(entprovider.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := pc.mutation.ProviderGitURL(); ok {
		_spec.SetField(entprovider.FieldProviderGitURL, field.TypeString, value)
		_node.ProviderGitURL = value
	}
	if value, ok := pc.mutation.ProviderVersion(); ok {
		_spec.SetField(entprovider.FieldProviderVersion, field.TypeString, value)
		_node.ProviderVersion = value
	}
	if value, ok := pc.mutation.ConfigBytes(); ok {
		_spec.SetField(entprovider.FieldConfigBytes, field.TypeBytes, value)
		_node.ConfigBytes = value
	}
	if value, ok := pc.mutation.IsLoaded(); ok {
		_spec.SetField(entprovider.FieldIsLoaded, field.TypeBool, value)
		_node.IsLoaded = value
	}
	if nodes := pc.mutation.BlueprintsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   entprovider.BlueprintsTable,
			Columns: []string{entprovider.BlueprintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProviderCreateBulk is the builder for creating many Provider entities in bulk.
type ProviderCreateBulk struct {
	config
	err      error
	builders []*ProviderCreate
}

// Save creates the Provider entities in the database.
func (pcb *ProviderCreateBulk) Save(ctx context.Context) ([]*Provider, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Provider, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProviderCreateBulk) SaveX(ctx context.Context) []*Provider {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProviderCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
