// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cble-platform/cble-backend/ent/blueprint"
	"github.com/cble-platform/cble-backend/ent/deployment"
	"github.com/cble-platform/cble-backend/ent/group"
	"github.com/cble-platform/cble-backend/ent/predicate"
	"github.com/cble-platform/cble-backend/ent/provider"
	"github.com/google/uuid"
)

// BlueprintQuery is the builder for querying Blueprint entities.
type BlueprintQuery struct {
	config
	ctx             *QueryContext
	order           []blueprint.OrderOption
	inters          []Interceptor
	predicates      []predicate.Blueprint
	withParentGroup *GroupQuery
	withProvider    *ProviderQuery
	withDeployments *DeploymentQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlueprintQuery builder.
func (bq *BlueprintQuery) Where(ps ...predicate.Blueprint) *BlueprintQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BlueprintQuery) Limit(limit int) *BlueprintQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BlueprintQuery) Offset(offset int) *BlueprintQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BlueprintQuery) Unique(unique bool) *BlueprintQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BlueprintQuery) Order(o ...blueprint.OrderOption) *BlueprintQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryParentGroup chains the current query on the "parent_group" edge.
func (bq *BlueprintQuery) QueryParentGroup() *GroupQuery {
	query := (&GroupClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blueprint.Table, blueprint.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blueprint.ParentGroupTable, blueprint.ParentGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProvider chains the current query on the "provider" edge.
func (bq *BlueprintQuery) QueryProvider() *ProviderQuery {
	query := (&ProviderClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blueprint.Table, blueprint.FieldID, selector),
			sqlgraph.To(provider.Table, provider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blueprint.ProviderTable, blueprint.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeployments chains the current query on the "deployments" edge.
func (bq *BlueprintQuery) QueryDeployments() *DeploymentQuery {
	query := (&DeploymentClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blueprint.Table, blueprint.FieldID, selector),
			sqlgraph.To(deployment.Table, deployment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, blueprint.DeploymentsTable, blueprint.DeploymentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Blueprint entity from the query.
// Returns a *NotFoundError when no Blueprint was found.
func (bq *BlueprintQuery) First(ctx context.Context) (*Blueprint, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blueprint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BlueprintQuery) FirstX(ctx context.Context) *Blueprint {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Blueprint ID from the query.
// Returns a *NotFoundError when no Blueprint ID was found.
func (bq *BlueprintQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blueprint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BlueprintQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Blueprint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Blueprint entity is found.
// Returns a *NotFoundError when no Blueprint entities are found.
func (bq *BlueprintQuery) Only(ctx context.Context) (*Blueprint, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blueprint.Label}
	default:
		return nil, &NotSingularError{blueprint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BlueprintQuery) OnlyX(ctx context.Context) *Blueprint {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Blueprint ID in the query.
// Returns a *NotSingularError when more than one Blueprint ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BlueprintQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blueprint.Label}
	default:
		err = &NotSingularError{blueprint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BlueprintQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Blueprints.
func (bq *BlueprintQuery) All(ctx context.Context) ([]*Blueprint, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Blueprint, *BlueprintQuery]()
	return withInterceptors[[]*Blueprint](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BlueprintQuery) AllX(ctx context.Context) []*Blueprint {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Blueprint IDs.
func (bq *BlueprintQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(blueprint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BlueprintQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BlueprintQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BlueprintQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BlueprintQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BlueprintQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BlueprintQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlueprintQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BlueprintQuery) Clone() *BlueprintQuery {
	if bq == nil {
		return nil
	}
	return &BlueprintQuery{
		config:          bq.config,
		ctx:             bq.ctx.Clone(),
		order:           append([]blueprint.OrderOption{}, bq.order...),
		inters:          append([]Interceptor{}, bq.inters...),
		predicates:      append([]predicate.Blueprint{}, bq.predicates...),
		withParentGroup: bq.withParentGroup.Clone(),
		withProvider:    bq.withProvider.Clone(),
		withDeployments: bq.withDeployments.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithParentGroup tells the query-builder to eager-load the nodes that are connected to
// the "parent_group" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlueprintQuery) WithParentGroup(opts ...func(*GroupQuery)) *BlueprintQuery {
	query := (&GroupClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withParentGroup = query
	return bq
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlueprintQuery) WithProvider(opts ...func(*ProviderQuery)) *BlueprintQuery {
	query := (&ProviderClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withProvider = query
	return bq
}

// WithDeployments tells the query-builder to eager-load the nodes that are connected to
// the "deployments" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlueprintQuery) WithDeployments(opts ...func(*DeploymentQuery)) *BlueprintQuery {
	query := (&DeploymentClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withDeployments = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Blueprint.Query().
//		GroupBy(blueprint.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BlueprintQuery) GroupBy(field string, fields ...string) *BlueprintGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlueprintGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = blueprint.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Blueprint.Query().
//		Select(blueprint.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BlueprintQuery) Select(fields ...string) *BlueprintSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BlueprintSelect{BlueprintQuery: bq}
	sbuild.label = blueprint.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlueprintSelect configured with the given aggregations.
func (bq *BlueprintQuery) Aggregate(fns ...AggregateFunc) *BlueprintSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BlueprintQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !blueprint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BlueprintQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Blueprint, error) {
	var (
		nodes       = []*Blueprint{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [3]bool{
			bq.withParentGroup != nil,
			bq.withProvider != nil,
			bq.withDeployments != nil,
		}
	)
	if bq.withParentGroup != nil || bq.withProvider != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blueprint.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Blueprint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Blueprint{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withParentGroup; query != nil {
		if err := bq.loadParentGroup(ctx, query, nodes, nil,
			func(n *Blueprint, e *Group) { n.Edges.ParentGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withProvider; query != nil {
		if err := bq.loadProvider(ctx, query, nodes, nil,
			func(n *Blueprint, e *Provider) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withDeployments; query != nil {
		if err := bq.loadDeployments(ctx, query, nodes,
			func(n *Blueprint) { n.Edges.Deployments = []*Deployment{} },
			func(n *Blueprint, e *Deployment) { n.Edges.Deployments = append(n.Edges.Deployments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BlueprintQuery) loadParentGroup(ctx context.Context, query *GroupQuery, nodes []*Blueprint, init func(*Blueprint), assign func(*Blueprint, *Group)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Blueprint)
	for i := range nodes {
		if nodes[i].blueprint_parent_group == nil {
			continue
		}
		fk := *nodes[i].blueprint_parent_group
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blueprint_parent_group" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BlueprintQuery) loadProvider(ctx context.Context, query *ProviderQuery, nodes []*Blueprint, init func(*Blueprint), assign func(*Blueprint, *Provider)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Blueprint)
	for i := range nodes {
		if nodes[i].blueprint_provider == nil {
			continue
		}
		fk := *nodes[i].blueprint_provider
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(provider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blueprint_provider" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BlueprintQuery) loadDeployments(ctx context.Context, query *DeploymentQuery, nodes []*Blueprint, init func(*Blueprint), assign func(*Blueprint, *Deployment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Blueprint)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Deployment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(blueprint.DeploymentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.deployment_blueprint
		if fk == nil {
			return fmt.Errorf(`foreign-key "deployment_blueprint" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deployment_blueprint" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BlueprintQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BlueprintQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blueprint.Table, blueprint.Columns, sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blueprint.FieldID)
		for i := range fields {
			if fields[i] != blueprint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BlueprintQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(blueprint.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = blueprint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlueprintGroupBy is the group-by builder for Blueprint entities.
type BlueprintGroupBy struct {
	selector
	build *BlueprintQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BlueprintGroupBy) Aggregate(fns ...AggregateFunc) *BlueprintGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BlueprintGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlueprintQuery, *BlueprintGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BlueprintGroupBy) sqlScan(ctx context.Context, root *BlueprintQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlueprintSelect is the builder for selecting fields of Blueprint entities.
type BlueprintSelect struct {
	*BlueprintQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BlueprintSelect) Aggregate(fns ...AggregateFunc) *BlueprintSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BlueprintSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlueprintQuery, *BlueprintSelect](ctx, bs.BlueprintQuery, bs, bs.inters, v)
}

func (bs *BlueprintSelect) sqlScan(ctx context.Context, root *BlueprintQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
