// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cble-platform/cble-backend/ent/blueprint"
	"github.com/cble-platform/cble-backend/ent/deployment"
	"github.com/cble-platform/cble-backend/ent/predicate"
	"github.com/cble-platform/cble-backend/ent/user"
	"github.com/google/uuid"
)

// DeploymentQuery is the builder for querying Deployment entities.
type DeploymentQuery struct {
	config
	ctx           *QueryContext
	order         []deployment.OrderOption
	inters        []Interceptor
	predicates    []predicate.Deployment
	withBlueprint *BlueprintQuery
	withRequester *UserQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeploymentQuery builder.
func (dq *DeploymentQuery) Where(ps ...predicate.Deployment) *DeploymentQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DeploymentQuery) Limit(limit int) *DeploymentQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DeploymentQuery) Offset(offset int) *DeploymentQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DeploymentQuery) Unique(unique bool) *DeploymentQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DeploymentQuery) Order(o ...deployment.OrderOption) *DeploymentQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryBlueprint chains the current query on the "blueprint" edge.
func (dq *DeploymentQuery) QueryBlueprint() *BlueprintQuery {
	query := (&BlueprintClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deployment.Table, deployment.FieldID, selector),
			sqlgraph.To(blueprint.Table, blueprint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, deployment.BlueprintTable, deployment.BlueprintColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequester chains the current query on the "requester" edge.
func (dq *DeploymentQuery) QueryRequester() *UserQuery {
	query := (&UserClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deployment.Table, deployment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, deployment.RequesterTable, deployment.RequesterColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Deployment entity from the query.
// Returns a *NotFoundError when no Deployment was found.
func (dq *DeploymentQuery) First(ctx context.Context) (*Deployment, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deployment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DeploymentQuery) FirstX(ctx context.Context) *Deployment {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Deployment ID from the query.
// Returns a *NotFoundError when no Deployment ID was found.
func (dq *DeploymentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deployment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DeploymentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Deployment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Deployment entity is found.
// Returns a *NotFoundError when no Deployment entities are found.
func (dq *DeploymentQuery) Only(ctx context.Context) (*Deployment, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deployment.Label}
	default:
		return nil, &NotSingularError{deployment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DeploymentQuery) OnlyX(ctx context.Context) *Deployment {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Deployment ID in the query.
// Returns a *NotSingularError when more than one Deployment ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DeploymentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deployment.Label}
	default:
		err = &NotSingularError{deployment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DeploymentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Deployments.
func (dq *DeploymentQuery) All(ctx context.Context) ([]*Deployment, error) {
	ctx = setContextOp(ctx, dq.ctx, "All")
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Deployment, *DeploymentQuery]()
	return withInterceptors[[]*Deployment](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DeploymentQuery) AllX(ctx context.Context) []*Deployment {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Deployment IDs.
func (dq *DeploymentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, "IDs")
	if err = dq.Select(deployment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DeploymentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DeploymentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, "Count")
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DeploymentQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DeploymentQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DeploymentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, "Exist")
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DeploymentQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeploymentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DeploymentQuery) Clone() *DeploymentQuery {
	if dq == nil {
		return nil
	}
	return &DeploymentQuery{
		config:        dq.config,
		ctx:           dq.ctx.Clone(),
		order:         append([]deployment.OrderOption{}, dq.order...),
		inters:        append([]Interceptor{}, dq.inters...),
		predicates:    append([]predicate.Deployment{}, dq.predicates...),
		withBlueprint: dq.withBlueprint.Clone(),
		withRequester: dq.withRequester.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithBlueprint tells the query-builder to eager-load the nodes that are connected to
// the "blueprint" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DeploymentQuery) WithBlueprint(opts ...func(*BlueprintQuery)) *DeploymentQuery {
	query := (&BlueprintClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withBlueprint = query
	return dq
}

// WithRequester tells the query-builder to eager-load the nodes that are connected to
// the "requester" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DeploymentQuery) WithRequester(opts ...func(*UserQuery)) *DeploymentQuery {
	query := (&UserClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withRequester = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Deployment.Query().
//		GroupBy(deployment.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DeploymentQuery) GroupBy(field string, fields ...string) *DeploymentGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeploymentGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = deployment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Deployment.Query().
//		Select(deployment.FieldName).
//		Scan(ctx, &v)
func (dq *DeploymentQuery) Select(fields ...string) *DeploymentSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DeploymentSelect{DeploymentQuery: dq}
	sbuild.label = deployment.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeploymentSelect configured with the given aggregations.
func (dq *DeploymentQuery) Aggregate(fns ...AggregateFunc) *DeploymentSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DeploymentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !deployment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DeploymentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Deployment, error) {
	var (
		nodes       = []*Deployment{}
		withFKs     = dq.withFKs
		_spec       = dq.querySpec()
		loadedTypes = [2]bool{
			dq.withBlueprint != nil,
			dq.withRequester != nil,
		}
	)
	if dq.withBlueprint != nil || dq.withRequester != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Deployment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Deployment{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withBlueprint; query != nil {
		if err := dq.loadBlueprint(ctx, query, nodes, nil,
			func(n *Deployment, e *Blueprint) { n.Edges.Blueprint = e }); err != nil {
			return nil, err
		}
	}
	if query := dq.withRequester; query != nil {
		if err := dq.loadRequester(ctx, query, nodes, nil,
			func(n *Deployment, e *User) { n.Edges.Requester = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DeploymentQuery) loadBlueprint(ctx context.Context, query *BlueprintQuery, nodes []*Deployment, init func(*Deployment), assign func(*Deployment, *Blueprint)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Deployment)
	for i := range nodes {
		if nodes[i].deployment_blueprint == nil {
			continue
		}
		fk := *nodes[i].deployment_blueprint
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blueprint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deployment_blueprint" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dq *DeploymentQuery) loadRequester(ctx context.Context, query *UserQuery, nodes []*Deployment, init func(*Deployment), assign func(*Deployment, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Deployment)
	for i := range nodes {
		if nodes[i].deployment_requester == nil {
			continue
		}
		fk := *nodes[i].deployment_requester
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deployment_requester" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dq *DeploymentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DeploymentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.FieldID)
		for i := range fields {
			if fields[i] != deployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DeploymentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(deployment.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = deployment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeploymentGroupBy is the group-by builder for Deployment entities.
type DeploymentGroupBy struct {
	selector
	build *DeploymentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DeploymentGroupBy) Aggregate(fns ...AggregateFunc) *DeploymentGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DeploymentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, "GroupBy")
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeploymentQuery, *DeploymentGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DeploymentGroupBy) sqlScan(ctx context.Context, root *DeploymentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeploymentSelect is the builder for selecting fields of Deployment entities.
type DeploymentSelect struct {
	*DeploymentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DeploymentSelect) Aggregate(fns ...AggregateFunc) *DeploymentSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DeploymentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, "Select")
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeploymentQuery, *DeploymentSelect](ctx, ds.DeploymentQuery, ds, ds.inters, v)
}

func (ds *DeploymentSelect) sqlScan(ctx context.Context, root *DeploymentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
