// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cble-platform/cble-backend/engine/models"
	"github.com/cble-platform/cble-backend/ent/blueprint"
	"github.com/cble-platform/cble-backend/ent/predicate"
	"github.com/cble-platform/cble-backend/ent/resource"
	"github.com/google/uuid"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceMutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (ru *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *ResourceUpdate) SetUpdatedAt(t time.Time) *ResourceUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetKey sets the "key" field.
func (ru *ResourceUpdate) SetKey(s string) *ResourceUpdate {
	ru.mutation.SetKey(s)
	return ru
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (ru *ResourceUpdate) SetNillableKey(s *string) *ResourceUpdate {
	if s != nil {
		ru.SetKey(*s)
	}
	return ru
}

// SetObject sets the "object" field.
func (ru *ResourceUpdate) SetObject(m *models.Object) *ResourceUpdate {
	ru.mutation.SetObject(m)
	return ru
}

// SetBlueprintID sets the "blueprint" edge to the Blueprint entity by ID.
func (ru *ResourceUpdate) SetBlueprintID(id uuid.UUID) *ResourceUpdate {
	ru.mutation.SetBlueprintID(id)
	return ru
}

// SetBlueprint sets the "blueprint" edge to the Blueprint entity.
func (ru *ResourceUpdate) SetBlueprint(b *Blueprint) *ResourceUpdate {
	return ru.SetBlueprintID(b.ID)
}

// AddDependsOnIDs adds the "depends_on" edge to the Resource entity by IDs.
func (ru *ResourceUpdate) AddDependsOnIDs(ids ...uuid.UUID) *ResourceUpdate {
	ru.mutation.AddDependsOnIDs(ids...)
	return ru
}

// AddDependsOn adds the "depends_on" edges to the Resource entity.
func (ru *ResourceUpdate) AddDependsOn(r ...*Resource) *ResourceUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddDependsOnIDs(ids...)
}

// AddRequiredByIDs adds the "required_by" edge to the Resource entity by IDs.
func (ru *ResourceUpdate) AddRequiredByIDs(ids ...uuid.UUID) *ResourceUpdate {
	ru.mutation.AddRequiredByIDs(ids...)
	return ru
}

// AddRequiredBy adds the "required_by" edges to the Resource entity.
func (ru *ResourceUpdate) AddRequiredBy(r ...*Resource) *ResourceUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRequiredByIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (ru *ResourceUpdate) Mutation() *ResourceMutation {
	return ru.mutation
}

// ClearBlueprint clears the "blueprint" edge to the Blueprint entity.
func (ru *ResourceUpdate) ClearBlueprint() *ResourceUpdate {
	ru.mutation.ClearBlueprint()
	return ru
}

// ClearDependsOn clears all "depends_on" edges to the Resource entity.
func (ru *ResourceUpdate) ClearDependsOn() *ResourceUpdate {
	ru.mutation.ClearDependsOn()
	return ru
}

// RemoveDependsOnIDs removes the "depends_on" edge to Resource entities by IDs.
func (ru *ResourceUpdate) RemoveDependsOnIDs(ids ...uuid.UUID) *ResourceUpdate {
	ru.mutation.RemoveDependsOnIDs(ids...)
	return ru
}

// RemoveDependsOn removes "depends_on" edges to Resource entities.
func (ru *ResourceUpdate) RemoveDependsOn(r ...*Resource) *ResourceUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveDependsOnIDs(ids...)
}

// ClearRequiredBy clears all "required_by" edges to the Resource entity.
func (ru *ResourceUpdate) ClearRequiredBy() *ResourceUpdate {
	ru.mutation.ClearRequiredBy()
	return ru
}

// RemoveRequiredByIDs removes the "required_by" edge to Resource entities by IDs.
func (ru *ResourceUpdate) RemoveRequiredByIDs(ids ...uuid.UUID) *ResourceUpdate {
	ru.mutation.RemoveRequiredByIDs(ids...)
	return ru
}

// RemoveRequiredBy removes "required_by" edges to Resource entities.
func (ru *ResourceUpdate) RemoveRequiredBy(r ...*Resource) *ResourceUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRequiredByIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ResourceUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ResourceUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *ResourceUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *ResourceUpdate) check() error {
	if _, ok := ru.mutation.BlueprintID(); ru.mutation.BlueprintCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Resource.blueprint"`)
	}
	return nil
}

func (ru *ResourceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ru.mutation.Key(); ok {
		_spec.SetField(resource.FieldKey, field.TypeString, value)
	}
	if value, ok := ru.mutation.Object(); ok {
		_spec.SetField(resource.FieldObject, field.TypeJSON, value)
	}
	if ru.mutation.BlueprintCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resource.BlueprintTable,
			Columns: []string{resource.BlueprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.BlueprintIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resource.BlueprintTable,
			Columns: []string{resource.BlueprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.DependsOnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedDependsOnIDs(); len(nodes) > 0 && !ru.mutation.DependsOnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.DependsOnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RequiredByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedRequiredByIDs(); len(nodes) > 0 && !ru.mutation.RequiredByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RequiredByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *ResourceUpdateOne) SetUpdatedAt(t time.Time) *ResourceUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetKey sets the "key" field.
func (ruo *ResourceUpdateOne) SetKey(s string) *ResourceUpdateOne {
	ruo.mutation.SetKey(s)
	return ruo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (ruo *ResourceUpdateOne) SetNillableKey(s *string) *ResourceUpdateOne {
	if s != nil {
		ruo.SetKey(*s)
	}
	return ruo
}

// SetObject sets the "object" field.
func (ruo *ResourceUpdateOne) SetObject(m *models.Object) *ResourceUpdateOne {
	ruo.mutation.SetObject(m)
	return ruo
}

// SetBlueprintID sets the "blueprint" edge to the Blueprint entity by ID.
func (ruo *ResourceUpdateOne) SetBlueprintID(id uuid.UUID) *ResourceUpdateOne {
	ruo.mutation.SetBlueprintID(id)
	return ruo
}

// SetBlueprint sets the "blueprint" edge to the Blueprint entity.
func (ruo *ResourceUpdateOne) SetBlueprint(b *Blueprint) *ResourceUpdateOne {
	return ruo.SetBlueprintID(b.ID)
}

// AddDependsOnIDs adds the "depends_on" edge to the Resource entity by IDs.
func (ruo *ResourceUpdateOne) AddDependsOnIDs(ids ...uuid.UUID) *ResourceUpdateOne {
	ruo.mutation.AddDependsOnIDs(ids...)
	return ruo
}

// AddDependsOn adds the "depends_on" edges to the Resource entity.
func (ruo *ResourceUpdateOne) AddDependsOn(r ...*Resource) *ResourceUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddDependsOnIDs(ids...)
}

// AddRequiredByIDs adds the "required_by" edge to the Resource entity by IDs.
func (ruo *ResourceUpdateOne) AddRequiredByIDs(ids ...uuid.UUID) *ResourceUpdateOne {
	ruo.mutation.AddRequiredByIDs(ids...)
	return ruo
}

// AddRequiredBy adds the "required_by" edges to the Resource entity.
func (ruo *ResourceUpdateOne) AddRequiredBy(r ...*Resource) *ResourceUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRequiredByIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (ruo *ResourceUpdateOne) Mutation() *ResourceMutation {
	return ruo.mutation
}

// ClearBlueprint clears the "blueprint" edge to the Blueprint entity.
func (ruo *ResourceUpdateOne) ClearBlueprint() *ResourceUpdateOne {
	ruo.mutation.ClearBlueprint()
	return ruo
}

// ClearDependsOn clears all "depends_on" edges to the Resource entity.
func (ruo *ResourceUpdateOne) ClearDependsOn() *ResourceUpdateOne {
	ruo.mutation.ClearDependsOn()
	return ruo
}

// RemoveDependsOnIDs removes the "depends_on" edge to Resource entities by IDs.
func (ruo *ResourceUpdateOne) RemoveDependsOnIDs(ids ...uuid.UUID) *ResourceUpdateOne {
	ruo.mutation.RemoveDependsOnIDs(ids...)
	return ruo
}

// RemoveDependsOn removes "depends_on" edges to Resource entities.
func (ruo *ResourceUpdateOne) RemoveDependsOn(r ...*Resource) *ResourceUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveDependsOnIDs(ids...)
}

// ClearRequiredBy clears all "required_by" edges to the Resource entity.
func (ruo *ResourceUpdateOne) ClearRequiredBy() *ResourceUpdateOne {
	ruo.mutation.ClearRequiredBy()
	return ruo
}

// RemoveRequiredByIDs removes the "required_by" edge to Resource entities by IDs.
func (ruo *ResourceUpdateOne) RemoveRequiredByIDs(ids ...uuid.UUID) *ResourceUpdateOne {
	ruo.mutation.RemoveRequiredByIDs(ids...)
	return ruo
}

// RemoveRequiredBy removes "required_by" edges to Resource entities.
func (ruo *ResourceUpdateOne) RemoveRequiredBy(r ...*Resource) *ResourceUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRequiredByIDs(ids...)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (ruo *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Resource entity.
func (ruo *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *ResourceUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *ResourceUpdateOne) check() error {
	if _, ok := ruo.mutation.BlueprintID(); ruo.mutation.BlueprintCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Resource.blueprint"`)
	}
	return nil
}

func (ruo *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.Key(); ok {
		_spec.SetField(resource.FieldKey, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Object(); ok {
		_spec.SetField(resource.FieldObject, field.TypeJSON, value)
	}
	if ruo.mutation.BlueprintCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resource.BlueprintTable,
			Columns: []string{resource.BlueprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.BlueprintIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resource.BlueprintTable,
			Columns: []string{resource.BlueprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blueprint.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.DependsOnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedDependsOnIDs(); len(nodes) > 0 && !ruo.mutation.DependsOnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.DependsOnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.DependsOnTable,
			Columns: resource.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RequiredByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedRequiredByIDs(); len(nodes) > 0 && !ruo.mutation.RequiredByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RequiredByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resource.RequiredByTable,
			Columns: resource.RequiredByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Resource{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
