// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/cble-platform/backend/ent/blueprint"
	"github.com/cble-platform/backend/ent/deployment"
	"github.com/cble-platform/backend/ent/group"
	"github.com/cble-platform/backend/ent/permission"
	"github.com/cble-platform/backend/ent/permissionpolicy"
	"github.com/cble-platform/backend/ent/schema"
	"github.com/cble-platform/backend/ent/user"
	"github.com/cble-platform/backend/ent/virtualizationprovider"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blueprintFields := schema.Blueprint{}.Fields()
	_ = blueprintFields
	// blueprintDescID is the schema descriptor for id field.
	blueprintDescID := blueprintFields[0].Descriptor()
	// blueprint.DefaultID holds the default value on creation for the id field.
	blueprint.DefaultID = blueprintDescID.Default.(func() uuid.UUID)
	deploymentFields := schema.Deployment{}.Fields()
	_ = deploymentFields
	// deploymentDescTemplateVars is the schema descriptor for template_vars field.
	deploymentDescTemplateVars := deploymentFields[1].Descriptor()
	// deployment.DefaultTemplateVars holds the default value on creation for the template_vars field.
	deployment.DefaultTemplateVars = deploymentDescTemplateVars.Default.(map[string]interface{})
	// deploymentDescDeploymentVars is the schema descriptor for deployment_vars field.
	deploymentDescDeploymentVars := deploymentFields[2].Descriptor()
	// deployment.DefaultDeploymentVars holds the default value on creation for the deployment_vars field.
	deployment.DefaultDeploymentVars = deploymentDescDeploymentVars.Default.(map[string]interface{})
	// deploymentDescIsActive is the schema descriptor for is_active field.
	deploymentDescIsActive := deploymentFields[3].Descriptor()
	// deployment.DefaultIsActive holds the default value on creation for the is_active field.
	deployment.DefaultIsActive = deploymentDescIsActive.Default.(map[string]int)
	// deploymentDescID is the schema descriptor for id field.
	deploymentDescID := deploymentFields[0].Descriptor()
	// deployment.DefaultID holds the default value on creation for the id field.
	deployment.DefaultID = deploymentDescID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() uuid.UUID)
	permissionpolicyFields := schema.PermissionPolicy{}.Fields()
	_ = permissionpolicyFields
	// permissionpolicyDescID is the schema descriptor for id field.
	permissionpolicyDescID := permissionpolicyFields[0].Descriptor()
	// permissionpolicy.DefaultID holds the default value on creation for the id field.
	permissionpolicy.DefaultID = permissionpolicyDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	virtualizationproviderFields := schema.VirtualizationProvider{}.Fields()
	_ = virtualizationproviderFields
	// virtualizationproviderDescID is the schema descriptor for id field.
	virtualizationproviderDescID := virtualizationproviderFields[0].Descriptor()
	// virtualizationprovider.DefaultID holds the default value on creation for the id field.
	virtualizationprovider.DefaultID = virtualizationproviderDescID.Default.(func() uuid.UUID)
}
