// Code generated by github.com/cble-platform/cble-backend, DO NOT EDIT.

package actions

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/99designs/gqlgen/graphql"
)

type PermissionAction string

// The following is an enum for use in the GraphQL Schema
/*
enum Action {
  blueprint_list
  blueprint_create
  blueprint_get
  blueprint_update
  blueprint_delete
  blueprint_deploy
  deployment_list
  deployment_create
  deployment_get
  deployment_update
  deployment_delete
  deployment_destroy
  deployment_redeploy
  deployment_power
  deployment_console
  group_list
  group_create
  group_get
  group_update
  group_delete
  permission_list
  permission_get
  permission_grant
  permission_revoke
  provider_list
  provider_create
  provider_get
  provider_update
  provider_delete
  provider_load
  provider_unload
  provider_configure
  user_list
  user_create
  user_get
  user_update
  user_delete
}
*/

const (
	// Blueprint
	ActionBlueprintList   PermissionAction = "blueprint_list"
	ActionBlueprintCreate PermissionAction = "blueprint_create"
	ActionBlueprintGet    PermissionAction = "blueprint_get"
	ActionBlueprintUpdate PermissionAction = "blueprint_update"
	ActionBlueprintDelete PermissionAction = "blueprint_delete"
	ActionBlueprintDeploy PermissionAction = "blueprint_deploy"
	// Deployment
	ActionDeploymentList     PermissionAction = "deployment_list"
	ActionDeploymentCreate   PermissionAction = "deployment_create"
	ActionDeploymentGet      PermissionAction = "deployment_get"
	ActionDeploymentUpdate   PermissionAction = "deployment_update"
	ActionDeploymentDelete   PermissionAction = "deployment_delete"
	ActionDeploymentDestroy  PermissionAction = "deployment_destroy"
	ActionDeploymentRedeploy PermissionAction = "deployment_redeploy"
	ActionDeploymentPower    PermissionAction = "deployment_power"
	ActionDeploymentConsole  PermissionAction = "deployment_console"
	// Group
	ActionGroupList   PermissionAction = "group_list"
	ActionGroupCreate PermissionAction = "group_create"
	ActionGroupGet    PermissionAction = "group_get"
	ActionGroupUpdate PermissionAction = "group_update"
	ActionGroupDelete PermissionAction = "group_delete"
	// Permission
	ActionPermissionList   PermissionAction = "permission_list"
	ActionPermissionGet    PermissionAction = "permission_get"
	ActionPermissionGrant  PermissionAction = "permission_grant"
	ActionPermissionRevoke PermissionAction = "permission_revoke"
	// Provider
	ActionProviderList      PermissionAction = "provider_list"
	ActionProviderCreate    PermissionAction = "provider_create"
	ActionProviderGet       PermissionAction = "provider_get"
	ActionProviderUpdate    PermissionAction = "provider_update"
	ActionProviderDelete    PermissionAction = "provider_delete"
	ActionProviderLoad      PermissionAction = "provider_load"
	ActionProviderUnload    PermissionAction = "provider_unload"
	ActionProviderConfigure PermissionAction = "provider_configure"
	// User
	ActionUserList   PermissionAction = "user_list"
	ActionUserCreate PermissionAction = "user_create"
	ActionUserGet    PermissionAction = "user_get"
	ActionUserUpdate PermissionAction = "user_update"
	ActionUserDelete PermissionAction = "user_delete"
	// Returned for any potential errors
	ActionUnknown PermissionAction = "unknown"
)

// String strips the object-specific prefix from
func (p PermissionAction) DisplayString() string {
	if before, after, ok := strings.Cut(string(p), "_"); !ok {
		return before
	} else {
		return after
	}
}

var actionMap = map[string]map[string]PermissionAction{
	// Blueprint
	"blueprint": {
		"list":   ActionBlueprintList,
		"create": ActionBlueprintCreate,
		"get":    ActionBlueprintGet,
		"update": ActionBlueprintUpdate,
		"delete": ActionBlueprintDelete,
		"deploy": ActionBlueprintDeploy,
	},
	// Deployment
	"deployment": {
		"list":     ActionDeploymentList,
		"create":   ActionDeploymentCreate,
		"get":      ActionDeploymentGet,
		"update":   ActionDeploymentUpdate,
		"delete":   ActionDeploymentDelete,
		"destroy":  ActionDeploymentDestroy,
		"redeploy": ActionDeploymentRedeploy,
		"power":    ActionDeploymentPower,
		"console":  ActionDeploymentConsole,
	},
	// Group
	"group": {
		"list":   ActionGroupList,
		"create": ActionGroupCreate,
		"get":    ActionGroupGet,
		"update": ActionGroupUpdate,
		"delete": ActionGroupDelete,
	},
	// Permission
	"permission": {
		"list":   ActionPermissionList,
		"get":    ActionPermissionGet,
		"grant":  ActionPermissionGrant,
		"revoke": ActionPermissionRevoke,
	},
	// Provider
	"provider": {
		"list":      ActionProviderList,
		"create":    ActionProviderCreate,
		"get":       ActionProviderGet,
		"update":    ActionProviderUpdate,
		"delete":    ActionProviderDelete,
		"load":      ActionProviderLoad,
		"unload":    ActionProviderUnload,
		"configure": ActionProviderConfigure,
	},
	// User
	"user": {
		"list":   ActionUserList,
		"create": ActionUserCreate,
		"get":    ActionUserGet,
		"update": ActionUserUpdate,
		"delete": ActionUserDelete,
	},
}

// Returns a PermissionAction for a given object and action
func Get(object string, action string) PermissionAction {
	pa, ok := actionMap[strings.ToLower(object)][strings.ToLower(action)]
	if !ok {
		return ActionUnknown
	} else {
		return pa
	}
}

// Values provides list valid values for Enum.
func (PermissionAction) Values() (kinds []string) {
	for _, s := range []PermissionAction{
		ActionBlueprintList,
		ActionBlueprintCreate,
		ActionBlueprintGet,
		ActionBlueprintUpdate,
		ActionBlueprintDelete,
		ActionBlueprintDeploy,
		ActionDeploymentList,
		ActionDeploymentCreate,
		ActionDeploymentGet,
		ActionDeploymentUpdate,
		ActionDeploymentDelete,
		ActionDeploymentDestroy,
		ActionDeploymentRedeploy,
		ActionDeploymentPower,
		ActionDeploymentConsole,
		ActionGroupList,
		ActionGroupCreate,
		ActionGroupGet,
		ActionGroupUpdate,
		ActionGroupDelete,
		ActionPermissionList,
		ActionPermissionGet,
		ActionPermissionGrant,
		ActionPermissionRevoke,
		ActionProviderList,
		ActionProviderCreate,
		ActionProviderGet,
		ActionProviderUpdate,
		ActionProviderDelete,
		ActionProviderLoad,
		ActionProviderUnload,
		ActionProviderConfigure,
		ActionUserList,
		ActionUserCreate,
		ActionUserGet,
		ActionUserUpdate,
		ActionUserDelete,
		ActionUnknown,
	} {
		kinds = append(kinds, string(s))
	}
	return
}

func MarshalUUID(val PermissionAction) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := json.NewEncoder(w).Encode(val)
		if err != nil {
			panic(err)
		}
	})
}

func UnmarshalUUID(v interface{}) (PermissionAction, error) {
	if m, ok := v.(string); ok {
		return PermissionAction(m), nil
	}

	return ActionUnknown, fmt.Errorf("%T is not a valid action", v)
}
