// Code generated by github.com/cble-platform/cble-backend, DO NOT EDIT.

package actions

import "strings"

type PermissionAction string

const (
	// Blueprint
	ActionBlueprintList   PermissionAction = "blueprint_list"
	ActionBlueprintCreate PermissionAction = "blueprint_create"
	ActionBlueprintGet    PermissionAction = "blueprint_get"
	ActionBlueprintUpdate PermissionAction = "blueprint_update"
	ActionBlueprintDelete PermissionAction = "blueprint_delete"
	ActionBlueprintDeploy PermissionAction = "blueprint_deploy"
	// Deployment
	ActionDeploymentList     PermissionAction = "deployment_list"
	ActionDeploymentCreate   PermissionAction = "deployment_create"
	ActionDeploymentGet      PermissionAction = "deployment_get"
	ActionDeploymentUpdate   PermissionAction = "deployment_update"
	ActionDeploymentDelete   PermissionAction = "deployment_delete"
	ActionDeploymentDestroy  PermissionAction = "deployment_destroy"
	ActionDeploymentRedeploy PermissionAction = "deployment_redeploy"
	ActionDeploymentConsole  PermissionAction = "deployment_console"
	// Group
	ActionGroupList   PermissionAction = "group_list"
	ActionGroupCreate PermissionAction = "group_create"
	ActionGroupGet    PermissionAction = "group_get"
	ActionGroupUpdate PermissionAction = "group_update"
	ActionGroupDelete PermissionAction = "group_delete"
	// Permission
	ActionPermissionList   PermissionAction = "permission_list"
	ActionPermissionCreate PermissionAction = "permission_create"
	ActionPermissionGet    PermissionAction = "permission_get"
	ActionPermissionUpdate PermissionAction = "permission_update"
	ActionPermissionDelete PermissionAction = "permission_delete"
	// Provider
	ActionProviderList      PermissionAction = "provider_list"
	ActionProviderCreate    PermissionAction = "provider_create"
	ActionProviderGet       PermissionAction = "provider_get"
	ActionProviderUpdate    PermissionAction = "provider_update"
	ActionProviderDelete    PermissionAction = "provider_delete"
	ActionProviderLoad      PermissionAction = "provider_load"
	ActionProviderUnload    PermissionAction = "provider_unload"
	ActionProviderConfigure PermissionAction = "provider_configure"
	// User
	ActionUserList   PermissionAction = "user_list"
	ActionUserCreate PermissionAction = "user_create"
	ActionUserGet    PermissionAction = "user_get"
	ActionUserUpdate PermissionAction = "user_update"
	ActionUserDelete PermissionAction = "user_delete"
	// Returned for any potential errors
	ActionUnknown PermissionAction = "unknown"
)

// String strips the object-specific prefix from
func (p PermissionAction) DisplayString() string {
	if before, after, ok := strings.Cut(string(p), "_"); !ok {
		return before
	} else {
		return after
	}
}

var actionMap = map[string]map[string]PermissionAction{
	// Blueprint
	"blueprint": {
		"list":   ActionBlueprintList,
		"create": ActionBlueprintCreate,
		"get":    ActionBlueprintGet,
		"update": ActionBlueprintUpdate,
		"delete": ActionBlueprintDelete,
		"deploy": ActionBlueprintDeploy,
	},
	// Deployment
	"deployment": {
		"list":     ActionDeploymentList,
		"create":   ActionDeploymentCreate,
		"get":      ActionDeploymentGet,
		"update":   ActionDeploymentUpdate,
		"delete":   ActionDeploymentDelete,
		"destroy":  ActionDeploymentDestroy,
		"redeploy": ActionDeploymentRedeploy,
		"console":  ActionDeploymentConsole,
	},
	// Group
	"group": {
		"list":   ActionGroupList,
		"create": ActionGroupCreate,
		"get":    ActionGroupGet,
		"update": ActionGroupUpdate,
		"delete": ActionGroupDelete,
	},
	// Permission
	"permission": {
		"list":   ActionPermissionList,
		"create": ActionPermissionCreate,
		"get":    ActionPermissionGet,
		"update": ActionPermissionUpdate,
		"delete": ActionPermissionDelete,
	},
	// Provider
	"provider": {
		"list":      ActionProviderList,
		"create":    ActionProviderCreate,
		"get":       ActionProviderGet,
		"update":    ActionProviderUpdate,
		"delete":    ActionProviderDelete,
		"load":      ActionProviderLoad,
		"unload":    ActionProviderUnload,
		"configure": ActionProviderConfigure,
	},
	// User
	"user": {
		"list":   ActionUserList,
		"create": ActionUserCreate,
		"get":    ActionUserGet,
		"update": ActionUserUpdate,
		"delete": ActionUserDelete,
	},
}

// Returns a PermissionAction for a given object and action
func Get(object string, action string) PermissionAction {
	pa, ok := actionMap[strings.ToLower(object)][strings.ToLower(action)]
	if !ok {
		return ActionUnknown
	} else {
		return pa
	}
}

// Values provides list valid values for Enum.
func (PermissionAction) Values() (kinds []string) {
	for _, s := range []PermissionAction{
		ActionBlueprintList,
		ActionBlueprintCreate,
		ActionBlueprintGet,
		ActionBlueprintUpdate,
		ActionBlueprintDelete,
		ActionBlueprintDeploy,
		ActionDeploymentList,
		ActionDeploymentCreate,
		ActionDeploymentGet,
		ActionDeploymentUpdate,
		ActionDeploymentDelete,
		ActionDeploymentDestroy,
		ActionDeploymentRedeploy,
		ActionDeploymentConsole,
		ActionGroupList,
		ActionGroupCreate,
		ActionGroupGet,
		ActionGroupUpdate,
		ActionGroupDelete,
		ActionPermissionList,
		ActionPermissionCreate,
		ActionPermissionGet,
		ActionPermissionUpdate,
		ActionPermissionDelete,
		ActionProviderList,
		ActionProviderCreate,
		ActionProviderGet,
		ActionProviderUpdate,
		ActionProviderDelete,
		ActionProviderLoad,
		ActionProviderUnload,
		ActionProviderConfigure,
		ActionUserList,
		ActionUserCreate,
		ActionUserGet,
		ActionUserUpdate,
		ActionUserDelete,
		ActionUnknown,
	} {
		kinds = append(kinds, string(s))
	}
	return
}
